ingress:
  enabled: false
imagePullSecrets: []
replicaCount: 1
image:
  repository: irib-dwp-frontend
  pullPolicy: IfNotPresent
  tag: "staging"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
env:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_API_URL: "http://dwp-backend.dwp-staging.svc.cluster.local/api/v1"
  NEXT_PUBLIC_WS_URL: "ws://dwp-backend.dwp-staging.svc.cluster.local"
  extra: []

probes:
  liveness:
    httpGet: null
    tcpSocket:
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    httpGet: null
    tcpSocket:
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  startup:
    httpGet: null
    tcpSocket:
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 30
